package ch.fhnw.jobannotations;

import me.xdrop.fuzzywuzzy.FuzzySearch;
import me.xdrop.fuzzywuzzy.model.ExtractedResult;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.IOException;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author Hoang
 */
public class JobTitleParser {
    private static String REGEX_GENDER = "\\(?[wm]\\/[wm]\\)?";
    private static String REGEX_WORKLOAD = "\\(?(\\d+%?\\s?-\\s?)?\\d+%\\)?";
    private static String REGEX_SENTENCE = ".*[.?!]$";

    public void parseJobTitleParser(String url) {
        try {

            // need http protocol
            Document doc = Jsoup.connect(url).get();

            // get page title
            String title = doc.title();
            System.out.println("url title : " + title);

            // get all heading tags <h1> to <h6>
            Set<String> headerTexts = new HashSet<>();
            for (int i = 0; i < 6; i++) {
                String tagName = "h" + (i + 1);
                Elements headers = doc.select(tagName);
                for (Element header : headers) {
                    headerTexts.add(header.text());
                }
            }

            // clean all header texts
            Set<String> cleanedHeaderTexts = new HashSet<>();
            for (String headerText : headerTexts) {
                String probableJobTitleText = cleanProbableJobTitleText(headerText);
                cleanedHeaderTexts.add(probableJobTitleText);
            }

            // remove entries with high chance of not being a job title
            Set<String> possibleJobTitles = new HashSet<>();
            for (String cleanedHeaderText : cleanedHeaderTexts) {
                if (isProbablyNotJobTitle(cleanedHeaderText)) {
                    continue;
                }

                possibleJobTitles.add(cleanedHeaderText);
            }

            System.out.println("headers: " + possibleJobTitles.toString());

            Set<String> probableJobTitles = new HashSet<>();
            for (String possibleJobTitle : possibleJobTitles) {
                for (String jobTitleSuffix : JOB_TITLE_SUFFIXES) {
                    if (possibleJobTitle.toLowerCase().contains(jobTitleSuffix)) {
                        probableJobTitles.add(possibleJobTitle);
                        System.out.println(possibleJobTitle);
                    }
                }
            }
            System.out.println("_________________");

            String jobTitleWithHighestScrore = "";
            int highestScore = 0;
            for (String probableJobTitle : probableJobTitles) {
                ExtractedResult extractedResult = FuzzySearch.extractOne(probableJobTitle, JOB_TITLES);
                System.out.println(extractedResult.toString());
                int score = extractedResult.getScore();
                if (score > highestScore) {
                    jobTitleWithHighestScrore = probableJobTitle;
                }
            }

            System.out.println(jobTitleWithHighestScrore);

            System.out.println("_________________");

            for (String possibleJobTitle : possibleJobTitles) {
                ExtractedResult extractedResult = FuzzySearch.extractOne(possibleJobTitle, JOB_TITLES);
                System.out.println(extractedResult.toString());
            }


        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private String cleanProbableJobTitleText(String probableJobTitleText) {
        probableJobTitleText = probableJobTitleText.replaceAll(REGEX_GENDER, "");
        probableJobTitleText = probableJobTitleText.replaceAll(REGEX_WORKLOAD, "");
        probableJobTitleText = probableJobTitleText.trim();
        return probableJobTitleText;
    }

    private boolean isProbablyNotJobTitle(String text) {
        // check if is a sentence
        Pattern pattern = Pattern.compile(REGEX_SENTENCE);
        Matcher matcher = pattern.matcher(text);
        if (matcher.matches()) {
            return true;
        }

        return false;
    }

    private static List<String> JOB_TITLE_SUFFIXES = new ArrayList<String>(){{
        add("administrator");
        add("angestellter");
        add("agent");
        add("analyst");
        add("analytiker");
        add("arbeiter");
        add("architekt");
        add("artist");
        add("assistent");
        add("bauer");
        add("begleiter");
        add("betreuer");
        add("berater");
        add("beratung");
        add("bewerter");
        add("biologe");
        add("consultant");
        add("designer");
        add("developer");
        add("elektroniker");
        add("engineer");
        add("entwickler");
        add("erzeuger");
        add("erzeugung");
        add("expert");
        add("experte");
        add("fahrer");
        add("fertiger");
        add("forscher");
        add("führer");
        add("gehilfe");
        add("gestalter");
        add("gestaltung");
        add("halter");
        add("helfer");
        add("hersteller");
        add("herstellung");
        add("händler");
        add("ingenieur");
        add("informatiker");
        add("installateur");
        add("journalist");
        add("lehrer");
        add("leger");
        add("leiter");
        add("konstrukteur");
        add("korrespondent");
        add("macher");
        add("manager");
        add("mechaniker");
        add("meister");
        add("monteur");
        add("pfleger");
        add("programmierer");
        add("prüfer");
        add("psychologe");
        add("pädagoge");
        add("redakteur");
        add("sekretär");
        add("spezialist");
        add("technik");
        add("techniker");
        add("technologe");
        add("trainer");
        add("vermittler");
        add("verkäufer");
        add("wart");
        add("wärter");
        add("wirt");
        add("wissenschafter");
        add("wissenschaftler");

        add("angestellte");
        add("bäuerin");
        add("biologin");
        add("gehilfin");
        add("psychologin");
        add("pädagogin");
        add("technologin");

        add("kaufmann");
        add("kauffrau");

        add("fachmann");
        add("fachfrau");
    }};

    private static List<String> JOB_TITLES = new ArrayList<String>(){{
        add("Agent");
        add("Analyst");
        add("Architekt");
        add("Assistent");
        add("Betreuer");
        add("Berater");
        add("Engineer");
        add("Entwickler");
        add("Gehilfe");
        add("Helfer");
        add("Ingenieur");
        add("Leiter");
        add("Manager");
        add("Programmierer");
        add("Sekretär");
        add("Techniker");
        add("Techniker");
        add("Wissenschafter");
        add("Wissenschaftler");
        add("");

        add("Asset Manager");
        add("Archäologe");
        add("Archäologin");
        add("Arbeitswissenschafter");
        add("Atem- und Sprechtrainer");
        add("Architekt");
        add("Audio Engineer");
        add("Applikationstechniker");
        add("App-Entwickler");
        add("Astronom");
        add("Anlagenelektrik");
        add("Astrologe");
        add("Astrologin");
        add("Agraringenieur");
        add("Animateur");
        add("Freizeitbetreuer");
        add("Art Director");
        add("Ausstellungstischler");
        add("Anzeigenkontakter");
        add("Aufnahmeleiter");
        add("Arabist");
        add("Afrikanist");
        add("Außenrequisiteur");
        add("Ausfertiger");
        add("Apparatebautechniker");
        add("Atomphysiker");
        add("Art Buyer");
        add("Automatisierungstechniker");
        add("Archäologe");
        add("Archäologin");
        add("Alltagsmanager");
        add("Aerobic-Trainer");
        add("Aufnahmetechniker");
        add("Anlageanalytiker");
        add("Arzthelfer");
        add("Auktionator");
        add("Antiquitäten- und Kunstgegenständehändler");
        add("Agrartechniker");
        add("Anwendungsberater");
        add("Ägyptologe/Ägyptologin");
        add("Apotheker");
        add("Agrarkaufmann/-frau");
        add("Autobusfahrer");
        add("Astrophysiker");
        add("Amtsvormund");
        add("Anglist");
        add("Amerikanist");
        add("Arbeitsvorbereiter");
        add("Agrartechniker");
        add("Agrarwirt");
        add("landwirtschaftliches Direktmarketing");
        add("Abfallbeauftragter");
        add("Abfallbeauftragte");
        add("Autoverkäufer");
        add("Außenhandelssekretär");
        add("Antriebstechniker");
        add("Agrarmanager");
        add("Adressmakler");
        add("Artist");
        add("Anlagenbautechniker");
        add("Applikations-Programmierer");
        add("Augenoptik");
        add("Abteilungsleiter");
        add("Amtsgehilfe");
        add("Amtsgehilfin");
        add("Astronaut");
        add("Antiquar");
        add("Anwendungstechniker");
        add("Anlage- und Vermögensberater");
        add("Arzt/Ärztin");
        add("Astrobiologe");
        add("Astrobiologin");
        add("Anwendungsprogrammierer");
        add("Autor");
        add("Artist-and-Repertoire-Manager");
        add("Abfallwirtschaftstechniker");
        add("Arbeitsplatzbewerter");
        add("ASIC-Techniker");
        add("Arbeits- und Organisationspsychologe");
        add("Arbeits- und Organisationspsychologin");
        add("Agrartechniker");
        add("Abfallberater");
        add("Altersforscher");
        add("Adressvermittler");
        add("Agrartechniker");
        add("Anthropologe");
        add("Anthropologin");
        add("3D-Artist");
        add("Asphaltierer");
        add("Allergologe");
        add("Allergologin");
        add("Altwarenhändler");
        add("Aktuar");
        add("Anlagenmonteur");
        add("Agrartechniker");
        add("Archiv-, Bibliotheks- und Informationsassistent");
        add("Auslandskorrespondent");
        add("Archivar");
        add("Auditor");
        add("Bauökologe");
        add("Bauökologin");
        add("Bügler");
        add("Bildhauer");
        add("Bautechniker");
        add("Blechblasinstrumentenerzeugung");
        add("Bioinformatiker");
        add("Behindertenbegleiter");
        add("Brunnenmacher");
        add("Bauingenieur");
        add("Bordtechniker");
        add("Baukaufmann/-frau");
        add("BlumenbinderIn und -händler");
        add("Bootbauer");
        add("Binder");
        add("Bewährungshelfer");
        add("Börsenmakler");
        add("Bühnentischler");
        add("Bekleidungsfertiger");
        add("Betriebstechniker");
        add("Barista");
        add("Balletttänzer");
        add("Bekleidungsgestaltung");
        add("Wäschewarenerzeugung");
        add("Beteiligungsmanager");
        add("Buchhalter");
        add("Bereichsleiter");
        add("Bekleidungstechniker");
        add("Bautechniker");
        add("Betriebsleiter");
        add("Badewärter");
        add("Saunawärter");
        add("Brau- und Getränketechnik");
        add("Bankkassier");
        add("Brunnen- und Grundbau");
        add("Buch- und Medienwirtschaft");
        add("Buch- und Pressegroßhandel");
        add("Bautechniker");
        add("Berufsfeuerwehrmann/-frau");
        add("Bergbautechniker");
        add("Buchhändler");
        add("Botschaftssektretär");
        add("Bildungs- und Berufsberater");
        add("Bildhauerei");
        add("Bote");
        add("Botin");
        add("Baumpfleger");
        add("Biomedizinischer Analytiker");
        add("Biomedizinische Analytikerin");
        add("Buchmacher");
        add("Bodenleger");
        add("Baumaschinist");
        add("Bildjournalist");
        add("Berufskraftfahrer");
        add("Berufsunteroffizier");
        add("Bauarbeiter");
        add("Bankangestellter");
        add("Bankangestellte");
        add("Bildungscontroller");
        add("Beschließer");
        add("Bekleidungsgestaltung");
        add("KürschnerIn und Säckler");
        add("Binnenschifffahrt");
        add("Bankangestellter");
        add("Bankangestellte");
        add("Barkeeper");
        add("Barmaid");
        add("Buchbinder");
        add("Bestatter");
        add("Biotechniker");
        add("Betonwarenerzeuger");
        add("Brief- und Paketzusteller");
        add("Bautechnischer Zeichner");
        add("Bautechnische Zeichnerin");
        add("Bergbauingenieur");
        add("Bioverfahrenstechniker");
        add("Bautechniker");
        add("Betriebswirt");
        add("Buffet- und Schankkraft");
        add("Bergwerkschlosser-Maschinenhäuer");
        add("Betriebsschlosser");
        add("Bautechniker");
        add("Bekleidungsgestaltung");
        add("ModistIn und Hutmacher");
        add("Bühnentechniker");
        add("Barmixer");
        add("Betriebslogistikkaufmann/-frau");
        add("Butler");
        add("Betriebsinformatiker");
        add("Börsenhändler");
        add("Berufskraftfahrer");
        add("Bühnenarbeiter");
        add("Betriebsdienstleistung");
        add("Baumaschinenführer");
        add("BrandschutzbeauftragteR");
        add("Baustofftechniker");
        add("Begleitlehrer");
        add("Integrationslehrer");
        add("Bewegungspädagoge/-pädagogin");
        add("Buch- und Medienwirtschaft");
        add("Verlag");
        add("Bibliothekar");
        add("Bürogehilfe");
        add("Bürogehilfin");
        add("Bauschlosser");
        add("Berufsdetektiv-Assistent");
        add("Bankettmanager");
        add("Burnout-Prophylaxe Trainer");
        add("Beschriftungsdesign und Werbetechnik");
        add("Bildungsberater");
        add("Baumaschinentechnik");
        add("Bauleiter");
        add("Baustellenkoordinator");
        add("Biochemiker");
        add("Bäcker");
        add("Billeteur");
        add("Biobauer");
        add("Biobäuerin");
        add("Büromaschinentechniker");
        add("Berufsdetektiv");
        add("Biomedical Engineer");
        add("Büroleiter");
        add("Bürokaufmann/-frau");
        add("Berufskraftfahrer");
        add("Güterbeförderung");
        add("Baustatiker");
        add("Bankangestellter");
        add("Bankangestellte");
        add("Bodyguard");
        add("Bibliothekar");
        add("Bautechniker");
        add("Botaniker");
        add("Beleuchter");
        add("Bankkaufmann/-frau");
        add("Buchhaltung");
        add("Bandagist");
        add("Bonbon- und Konfektmacher");
        add("Biotechnologe");
        add("Biotechnologin");
        add("Biologe");
        add("Biologin");
        add("Babysitter");
        add("Baumeister");
        add("Behindertenbetreuer");
        add("Bautischler");
        add("Biofeedbacktrainer");
        add("BrauerIn und Mälzer");
        add("Börsendisponent");
        add("Bilanzbuchhalter");
        add("Betriebselektriker");
        add("Broker");
        add("Berufskraftfahrer");
        add("Personenbeförderung");
        add("Betonfertigungstechnik");
        add("Bürsten- und Pinselmacher");
        add("Berufsoffizier");
        add("Büchsenmacher");
        add("Buchdrucker");
        add("Bekleidungsgestaltung");
        add("Herrenbekleidung");
        add("Bohrarbeiter");
        add("Bereiter");
        add("Bühnenbildner");
        add("Betonfertiger");
        add("Terrazzoherstellung");
        add("Bautechniker");
        add("Betonfertiger");
        add("Betonwarenerzeugung");
        add("Biobäcker");
        add("Büroangestellter");
        add("Büroangestellte");
        add("Bankangestellter");
        add("Bankangestellte");
        add("Biophysiker");
        add("Bühnenmaler");
        add("Bekleidungsgestaltung");
        add("Damenbekleidung");
        add("Betriebsrat");
        add("Betriebsrätin");
        add("Bildungsmanager");
        add("Botschafter");
        add("Buch- und Medienwirtschaft");
        add("Buch- und Musikalienhandel");
        add("Ballistiker");
        add("Bekleidungsgestaltung");
        add("Berufsfotograf");
        add("Bautechniker");
        add("Berufsschullehrer");
        add("Berg- und Schiführer");
        add("Blechschlosser");
        add("Bankangestellter");
        add("Bankangestellte");
        add("Betonfertiger");
        add("Betonwerksteinerzeugung");
        add("Briefträger");
        add("Bautechniker");
        add("Casting Director");
        add("Chip-Designer");
        add("Chemieverfahrenstechnik");
        add("Computer-Animationsdesigner");
        add("Community Manager");
        add("Cloud-Sicherheitstechniker");
        add("Content-Manager");
        add("Controller");
        add("Continuity");
        add("CAM-Techniker");
        add("Cloud-Engineer");
        add("Cutter");
        add("Chemiewerker");
        add("Computerlinguist");
        add("Computer Visualist");
        add("Computertechniker");
        add("Callcenter-Agent");
        add("Computer-Grafiker");
        add("Cloud-Architekt");
        add("Change Manager");
        add("Chemielaborant");
        add("Computerbuch-Autor");
        add("Chemie-Informatiker");
        add("Chemielabortechnik");
        add("Cost Engineer");
        add("Croupier");
        add("Croupière");
        add("Clinical Engineer");
        add("Cloud-Software-Engineer");
        add("Chemieingenieur");
        add("ChemikerIn für Analytische Chemie");
        add("Cloud-Netzwerktechniker");
        add("Clown");
        add("Conference Manager");
        add("ChemikerIn für Anorganische Chemie");
        add("Chocolatier");
        add("Choreograf");
        add("Customer Relation Manager");
        add("CAD-Techniker");
        add("Computer Forensiker");
        add("Computerspielprogrammierer");
        add("Compliance-Officer");
        add("Computeranimateur");
        add("ChemikerIn für Organische Chemie");
        add("Compositing Artist");
        add("Chemiker");
        add("Chirurgieinstrumentenerzeuger");
        add("Cloud-Systemtechniker");
        add("Computermathematiker");
        add("Chorsänger");
        add("Chauffeur");
        add("Creative Director");
        add("Chemietechniker");
        add("Catering-Spezialist");
        add("ChemikerIn für Technische Chemie");
        add("Campingplatzwart");
        add("ChemikerIn für Physikalische Chemie");
        add("Co-Pilot");
        add("Chefredakteur");
        add("Coach");
        add("Category Manager");
        add("Commerce ManagerIn E- & M-Commerce");
        add("Concierge Service Provider");
        add("Dreher");
        add("Data Scientist");
        add("Dachdecker");
        add("Drucker");
        add("Diplom-SozialbetreuerIn für Familienarbeit");
        add("Diplom-Sozialbetreuer");
        add("Dorfleiter");
        add("Drucktechnik");
        add("Rollenrotationsdruck");
        add("DJ");
        add("Denkmal- und Ensembelschützer");
        add("Database-Executive");
        add("Database-Developer");
        add("Dolmetscher");
        add("Destillateur");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("Deponiewart");
        add("Desktop Publisher");
        add("Datenschutzbeauftragte/r");
        add("Datensicherheitstechniker");
        add("Desinfektionsassistent");
        add("Diplomierte/r psychiatrische/r Gesundheits- und Krankenpfleger");
        add("Database-Professional");
        add("Drucktechnik");
        add("Database-Administrator");
        add("Database-Manager");
        add("Diätologe");
        add("Diätologin");
        add("Drucktechnik");
        add("Digitaldruck");
        add("Diversity Manager");
        add("Datenbank-Spezialist");
        add("Drachenflug- und Paragleitlehrer");
        add("Datenbank-Entwickler");
        add("Database-Analyst");
        add("Diplomierte/r Kardiotechniker");
        add("Druckvorstufentechnik");
        add("Drechsler");
        add("Dirigent");
        add("Drogist");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("Denk- und Gedächtnistrainer");
        add("Dekorateur");
        add("Datascout");
        add("Diplomierte/r Kinderkrankenpfleger");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("Devisenhändler");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("Dorfhelfer");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("Diakon");
        add("Dokumentar");
        add("Diplomierte/r medizinische/r Fachassistent");
        add("Datenbank-Administrator");
        add("Designer");
        add("Diplomierte/r Gesundheits- und Krankenpfleger");
        add("DV-Berater");
        add("Datenbank-Programmierer");
        add("DolmetscherIn, ÜbersetzerIn bei der EU");
        add("Diabetesberater");
        add("Dispatcher");
        add("Flugverkehr");
        add("Drucktechnik");
        add("Bogenflachdruck");
        add("Datenbankverwalter");
        add("Drehbuchautor");
        add("Diplomat");
        add("Database-Systems-Analyst");
        add("Diplomierte Medizinisch-technische Fachkraft");
        add("Drucktechnik");
        add("Siebdruck");
        add("Digital Marketing Spezialist");
        add("Desinfektionsgehilfe");
        add("Desinfektionsgehilfin");
        add("DessinateurIn für Stoffdruck");
        add("Datenmodellierer");
        add("Denkmal-, Fassaden- und Gebäudereiniger");
        add("Dramatiker");
        add("Direct-Marketing-Manager");
        add("Database-Engineer");
        add("Dramaturg");
        add("Data Security Advisor");
        add("Disponent");
        add("Datenanalyst");
        add("Direktberater");
        add("Detektiv");
        add("Datensicherheitsexpert");
        add("Damenkleidermacher");
        add("Erwachsenenbildner");
        add("Event-Manager");
        add("Einkäufer");
        add("Etui- und Kassettenerzeuger");
        add("Ergotherapeut");
        add("Energieberater");
        add("Event-Veranstalter");
        add("Einrichtungsberater");
        add("Erdwissenschafter");
        add("Eisenbahnelektrotechnik");
        add("Entwicklungsleiter");
        add("E-Commerce-Manager");
        add("Elektrotechnik");
        add("Energietechnik");
        add("Entsorgungs- und Recyclingfachmann/-frau");
        add("Abfall");
        add("Elektronik");
        add("Emailleur");
        add("Energetiker");
        add("Einzelhandel");
        add("Lebensmittelhandel");
        add("Einzelhandel");
        add("Feinkostfachverkauf");
        add("ElektromechanikerIn für Schwachstrom");
        add("Einzelhandel");
        add("Telekommunikation");
        add("Elektrotechniker");
        add("ElektromechanikerIn für Starkstrom");
        add("Ergonom");
        add("Elektronik");
        add("Kommunikationselektronik");
        add("Einzelhandel");
        add("Baustoffhandel");
        add("EDV-Systemtechnik");
        add("E-Learning Autor");
        add("Eisenbahntransporttechnik");
        add("EDV-Techniker");
        add("Entsorgungstechniker");
        add("Elektromaschinentechnik");
        add("Erdarbeiter");
        add("Elektronik");
        add("Angewandte Elektronik");
        add("E-Business-Projektmanager");
        add("Eisenbahnsicherungstechnik");
        add("EU-Beamter");
        add("EU-Beamtin");
        add("Elektroinstallationstechnik mit Schwerpunkt Prozessleit- und Bustechnik");
        add("Einzelhandel");
        add("Einrichtungsberatung");
        add("Elektronik");
        add("Angewandte Elektronik");
        add("EU-Beamter");
        add("EU-Beamtin");
        add("Einkäufer");
        add("Einzelhandel");
        add("Textilhandel");
        add("Elektrobetriebstechnik");
        add("Energietechniker");
        add("Windenergie");
        add("Eisenbahnfahrzeugtechnik");
        add("Entspannungstrainer");
        add("Erdölingenieur");
        add("Einzelhandel");
        add("Eisen- und Hartwaren");
        add("EDV-Consultant");
        add("EU-Beamter");
        add("EU-Beamtin");
        add("Ernährungswissenschafter");
        add("Edelsteinschleifer");
        add("Ernährungsberater");
        add("Entwicklungsökonom");
        add("Ethologe");
        add("Ethologin");
        add("Europa Assistent");
        add("Elektroenergietechnik");
        add("Erziehungswissenschafter");
        add("Elektronik");
        add("Mikrotechnik");
        add("E-Business-Key-Account-Manager");
        add("Elektriker");
        add("Einzelhandel");
        add("Sportartikel");
        add("Ethnologe");
        add("Ethnologin");
        add("ElektromechanikerIn und -maschinenbauer");
        add("Eisenbahnbetriebstechnik");
        add("EDV-Trainer");
        add("Entsorgungs- und Recyclingfachmann/-frau");
        add("Abwasser");
        add("Einkäufer");
        add("Elektroanlagentechnik");
        add("Ergotherapiegehilfe");
        add("Ergotherapiegehilfin");
        add("Exekutivbedienstete");
        add("Exekutivbediensteter im Polizeidienst");
        add("Essenzusteller");
        add("Einzelhandel");
        add("Parfümerie");
        add("E-Jurist");
        add("Erzieher");
        add("Energietechniker");
        add("Exportkaufmann/-frau");
        add("EU-Beamter");
        add("EU-Beamtin");
        add("Erdöltechniker");
        add("E-Commerce-Consultant");
        add("Elektroinstallationstechnik");
        add("EU-Beamter");
        add("EU-Beamtin");
        add("EU-Beamter");
        add("EU-Beamtin");
        add("Electronic-Marketing-Manager");
        add("Exekutivbedienstete");
        add("Exekutivbediensteter im Justizwachdienst");
        add("Elektronik");
        add("Informations- und Telekommunikationstechnik");
        add("Einzelhandel");
        add("Kraftfahrzeuge und Ersatzteile");
        add("Elektrobetriebstechnik mit Schwerpunkt Prozessleittechnik");
        add("Elektrotechnik");
        add("Automatisierungs- und Prozessleittechnik");
        add("Elektrotechnik");
        add("Eisenbahntelekommunikationstechnik");
        add("EDV-Servicetechniker");
        add("Eisenbahnfahrzeuginstandhaltungstechnik");
        add("Elektrotechnik");
        add("Anlagen- und Betriebstechnik");
        add("Entwicklungshelfer");
        add("Einzelhandel");
        add("Elektro-Elektronikberatung");
        add("Einzelhandel");
        add("Gartencenter");
        add("Elektrotechnik");
        add("Elektro- und Gebäudetechnik");
        add("Entlassungsmanager");
        add("E-Logistiker");
        add("Elektronik");
        add("Einzelhandel");
        add("Uhren- und Juwelenberatung");
        add("Elementarpädagoge");
        add("Elementarpädagogin");
        add("Einzelhandel");
        add("Elektromedizintechniker");
        add("Ehe- und Familienberater");
        add("Einzelhandel");
        add("Schuhe");
        add("Elektronik");
        add("Mikrotechnik");
        add("Erdölchemiker");
        add("Einzelhandel");
        add("Allgemeiner Einzelhandel");
        add("Elektroniker");
        add("EDV-Kaufmann/-frau");
        add("Elektroinstallateur");
        add("Finanzbeamter");
        add("Finanzbeamtin");
        add("Facharzt/-ärztin");
        add("Fotogravurzeichner");
        add("Flugverkehrsleiter");
        add("FacharbeiterIn Geflügelwirtschaft");
        add("Feinwerktechniker");
        add("Filmrestaurator");
        add("Fotomodel");
        add("Fiaker");
        add("Kutscher");
        add("Fleischer");
        add("Filmschnittmeister");
        add("Flugzeugspengler");
        add("Fremdenführer");
        add("Fernmeldebaumonteur");
        add("Fernlastfahrer");
        add("Fluglehrer");
        add("FacharbeiterIn Biomasseproduktion und land- und forstwirtschaftliche Bioenergiegewinnung");
        add("Filmvorführer");
        add("Filialleiter");
        add("Forstwart");
        add("Forstwirt");
        add("Farb- und Typberater");
        add("Feinmechaniker");
        add("Fraud Analyst");
        add("Fermentationstechniker");
        add("Financial Analyst");
        add("Fernsehsprecher");
        add("Flughafenarbeiter");
        add("Filmarchitekt");
        add("Fahrzeugbautechniker");
        add("Fluglotse");
        add("Fluglotsin");
        add("Fleischverkauf");
        add("Finanzdienstleistungskaufmann/-frau");
        add("Fleischverarbeitung");
        add("Forscher");
        add("Flugbegleiter");
        add("Flugsicherungsmechaniker");
        add("Fach- und Diplom-SozialbetreuerIn für Behindertenarbeit");
        add("Fondsverwalter");
        add("Friedhofs- und Ziergärtner");
        add("FleischuntersucherIn und Trichinenschauer");
        add("Flugzeugbautechniker");
        add("Figurant");
        add("Fassader");
        add("Fach-Sozialbetreuer");
        add("Diplom-Sozialbetreuer");
        add("FacharbeiterIn Bienenwirtschaft");
        add("Fahrradbote/-botin");
        add("Filmemacher");
        add("Filmregisseur");
        add("Franchise-Unternehmer");
        add("FacharbeiterIn Molkerei- und Käsereiwirtschaft");
        add("FacharbeiterIn landwirtschaftliche Lagerhaltung");
        add("Flugfernmelder");
        add("FacharbeiterIn Obstbau und Obstverwertung");
        add("Fitnesstrainer");
        add("Food & Beverage Manager");
        add("Flugdatenbearbeiter");
        add("FacharbeiterIn Fischereiwirtschaft");
        add("Fotojournalist");
        add("Fotoreporter");
        add("FacharbeiterIn ländliches Betriebs- und Haushaltsmanagement");
        add("Friedhofsaufseher");
        add("Fußballtrainer");
        add("Fleischwarenarbeiter");
        add("Fahrdienstleiter");
        add("Färber");
        add("Filmaufnahmeleiter");
        add("Förster");
        add("Fahrradmechaniker");
        add("Freizeitberater");
        add("Fahrzeugtapezierer");
        add("Flugfunker");
        add("Fassbinder");
        add("Feng Shui-Berater");
        add("Flüchtlingsbetreuer");
        add("Formenbauer");
        add("FacharbeiterIn Weinbau- und Kellerwirtschaft");
        add("Forsttechnik");
        add("Film- und Videoeditor");
        add("FriseurIn und Perückenmacher");
        add("Flachdrucker");
        add("Fertigungstechniker");
        add("Fach- und Diplom-SozialbetreuerIn für Behindertenbegleitung");
        add("FacharbeiterIn Forstwirtschaft");
        add("Fahrlehrer");
        add("Florist");
        add("Facility-Manager");
        add("Fußpfleger");
        add("Fotograf");
        add("FacharbeiterIn Landwirtschaft");
        add("Fahrzeugfertiger");
        add("Fitnessbetreuung");
        add("Feinoptik");
        add("Frächter");
        add("Finanzberater");
        add("Fakturist");
        add("Finanz- und Rechnungswesenassistenz");
        add("Flight Engineer");
        add("Fahrzeugelektroniker");
        add("Flugwettertechniker");
        add("Forensiker");
        add("Fensterputzer");
        add("FormerIn und Gießer");
        add("Freizeitpädagoge");
        add("Freizeitpädagogin");
        add("Flight-Attendant");
        add("Fremdsprachenkorrespondent");
        add("FacharbeiterIn Feldgemüsebau");
        add("Fondsmanager");
        add("Fahrschullehrer");
        add("Foto- und Multimediakaufmann/-frau");
        add("Finanzbuchhalter");
        add("Fach- und Diplom-SozialbetreuerIn für Altenarbeit");
        add("Fotograf");
        add("FacharbeiterIn Forstgarten- und Forstpflegewirtschaft");
        add("Forschungs- & Entwicklungstechniker");
        add("Fremdsprachensekretär");
        add("Fertigteilhausbau");
        add("FacharbeiterIn Pferdewirtschaft");
        add("FacharbeiterIn Gartenbau");
        add("Geschäftsführer");
        add("Grafiker");
        add("Gründungsberater");
        add("Geoinformationstechnik");
        add("Gentechnologe");
        add("Gentechnologin");
        add("Garten- und Grünflächengestaltung");
        add("Gerichtsdolmetscher");
        add("Gürtler");
        add("Gießereitechniker");
        add("Gas- und Wasserleitungsinstallateur");
        add("Geophysiker");
        add("Gehirnforscher");
        add("Garten- und Grünflächengestaltung");
        add("Landschaftsgärtnerei");
        add("Geragoge");
        add("Geragogin");
        add("Geograf");
        add("Gastronomiefachmann/-frau");
        add("Glasbautechnik");
        add("Glasbau");
        add("Gerichtsmediziner");
        add("Geoinformatiker");
        add("Großmaschinsticker");
        add("Gesundheitsmanager");
        add("Germanist");
        add("Gerberei");
        add("Gleisbautechnik");
        add("GefahrgutbeauftragteR");
        add("Geologe");
        add("Geologin");
        add("Glasmaler");
        add("Gießereitechnik");
        add("Golflehrer");
        add("Gesundheits- und Krankenschwester/-pfleger");
        add("Geologe");
        add("Geologin");
        add("Geotechniker");
        add("Geologe");
        add("Geologin");
        add("Garten- und Grünflächengestaltung");
        add("Greenkeeping");
        add("Gesteinshüttentechniker");
        add("Getreidemüller");
        add("Gerontologe");
        add("Gerontologin");
        add("Gipsassistent");
        add("Gold- und SilberschmiedIn und Juwelier");
        add("Gesundheitscontroller");
        add("Glashüttentechniker");
        add("Gießereitechnik");
        add("Nichteisenmetallguss");
        add("Garderobier");
        add("Garderobiere");
        add("Glasmacherei");
        add("Gebärdensprachdolmetscher");
        add("Geologe");
        add("Geologin");
        add("Graveur");
        add("Gold-, Silber- und Perlensticker");
        add("Gartenbautechniker");
        add("Gold-, Silber- und Metallschläger");
        add("Gesundheitstrainer");
        add("Grafiker");
        add("Glasgraveur");
        add("Glasgestalter");
        add("Gebäudetechniker");
        add("Ganzheitsmediziner");
        add("Geologe");
        add("Geologin");
        add("Getränkehersteller");
        add("Gesundheitspsychologe");
        add("Gesundheitspsychologin");
        add("Gymnastiktrainer");
        add("Genetiker");
        add("Ground Hostess");
        add("Gartencenterkaufmann/-frau");
        add("Genealoge");
        add("Genealogin");
        add("Gemeindepädagoge");
        add("Gemeindepädagogin");
        add("Gesundheitsökonom");
        add("Garderobier");
        add("Garderobiere");
        add("Geschirrkeramformer");
        add("Grafik-Designer");
        add("Galanteriespengler");
        add("Gießereitechnik");
        add("Eisen- und Stahlguss");
        add("GIS-Techniker");
        add("Geologe");
        add("Geologin");
        add("Geologe");
        add("Geologin");
        add("Geochemiker");
        add("Gerichtsvollzieher");
        add("Glasbautechnik");
        add("Großhandelskaufmann/-frau");
        add("GlasbläserIn und Glasinstrumentenerzeuger");
        add("Gesangslehrer");
        add("Ghostwriter");
        add("Geoinformationstechniker");
        add("Geologe");
        add("Geologin");
        add("Glaser");
        add("Galerist");
        add("Glasbautechnik");
        add("Glaskonstruktion");
        add("Gerüster");
        add("Gießereimechaniker");
        add("Game-Designer");
        add("Holztechnik");
        add("Sägetechnik");
        add("Hausdame/-herr im Hotel");
        add("Holzbautechniker");
        add("Hirt");
        add("Hausverwalter");
        add("Hochbautechniker");
        add("Heilmasseur");
        add("Hotelassistent");
        add("Hohlglasveredler");
        add("Gravur");
        add("Holz- und Steinbildhauer");
        add("Hotelsekretär");
        add("Humanbiologe");
        add("Humanbiologin");
        add("Harmonikamacher");
        add("Heraldiker");
        add("HR-Manager");
        add("Hotelkaufmann/-frau");
        add("Heilbademeister");
        add("Heilbademasseur");
        add("Haustechniker");
        add("Handelswissenschafter");
        add("Hotelportier");
        add("Holzspielzeugmacher");
        add("Hausbesorger");
        add("Hippotherapeut");
        add("Haushälter");
        add("Hotelkaufmann/-frau");
        add("HeilpädagogischeR Fachbetreuer");
        add("Hundeführer");
        add("Holzkaufmann/-frau");
        add("Hütteningenieur");
        add("Help-Desk-Agent");
        add("Heimhelfer");
        add("Hohlglasveredler");
        add("Glasmalerei");
        add("Hörgeräteakustiker");
        add("Hotel- und Gastgewerbeassistent");
        add("Holzwirt");
        add("Hundeabrichter");
        add("Hardware-Entwickler");
        add("Holz- und Sägetechnik");
        add("Hundekosmetiker");
        add("Heilbadegehilfe");
        add("Heilbadegehilfin");
        add("Hortpädagoge/-pädagogin");
        add("Handschuhmacher");
        add("Hafenmeister");
        add("Holzdesigner");
        add("Hubschrauberpilot");
        add("Hafner");
        add("Hebamme");
        add("Hufschmied");
        add("Herrenkleidermacher");
        add("Höhlenführer");
        add("Holzblasinstrumentenerzeugung");
        add("Heimleiter");
        add("Historiker");
        add("Hutmacher");
        add("Holztechniker");
        add("Handelsagent");
        add("Hohlglasveredler");
        add("Kugeln");
        add("Hüttenwerkschlosser");
        add("HohlglasschleiferIn- Kugeln");
        add("Holztechnik");
        add("Holztechnik");
        add("Fertigteilproduktion");
        add("Holztechnik");
        add("Werkstoffproduktion");
        add("Hofberater");
        add("Informationsbroker");
        add("Internet-");
        add("Intranet-Redakteur");
        add("Immobilienmakler");
        add("Immobilientreuhänder");
        add("IT-Forensiker");
        add("Interface-Designer");
        add("IC-Designer");
        add("Internet-Systembetreuer");
        add("Installationskünstler");
        add("Immobilienkaufmann/-frau");
        add("Innenrequisiteur");
        add("Internet-Scout");
        add("IT-Kaufmann/-frau");
        add("IT-Systemtechniker");
        add("InternationaleR Steuerberater");
        add("Indologe");
        add("Indologin");
        add("IT-Systemdesigner");
        add("IT-System-Kaufmann/-frau");
        add("IT-Betreuer");
        add("Investment Analyst");
        add("Isoliermonteur");
        add("Installations- und Gebäudetechnik");
        add("Lüftungstechnik");
        add("IT-Systemelektroniker");
        add("Integrationsbegleiter");
        add("Informationsmanager");
        add("Instruktor");
        add("Instrumentalmusiker");
        add("IT-Organisationsberater");
        add("IT-Systemanalytiker");
        add("Imam");
        add("IT-Berater");
        add("Informatiker");
        add("Instrumental- und Gesangspädagoge/-pädagogin");
        add("Installateur");
        add("Interkulturelle/r Trainer");
        add("Immobilienverwalter");
        add("IT-Projektmanager");
        add("Installations- und Gebäudetechnik");
        add("Gas- und Sanitärtechnik");
        add("Informationstechnologie");
        add("Technik");
        add("Intendant");
        add("Industriekaufmann/-frau");
        add("InternationaleR Wirtschaftsprüfer");
        add("Innovationsmanager");
        add("Informationstechnologie");
        add("Informatik");
        add("Interviewer");
        add("IT-Systemelektroniker");
        add("IT-Systemelektroniker");
        add("Industrietechniker");
        add("Innenarchitekt");
        add("Informationsdesigner");
        add("Informationstechniker");
        add("Industrielogistiker");
        add("Informatiker");
        add("IT-Elektronik");
        add("Innovationstechniker");
        add("Installations- und Gebäudetechnik");
        add("Innenausbauer");
        add("Inspizient");
        add("IT-Systemingenieur");
        add("IT-Systemelektroniker");
        add("Industrial-Designer");
        add("IT-Consultant");
        add("IT-System-Engineer");
        add("Informatikkaufmann/-frau");
        add("Illustrator");
        add("Industriekletterer");
        add("Industriekletterin");
        add("IT-Assistant");
        add("IT-Systemelektroniker");
        add("IT-Sicherheitsmanager");
        add("IT-Sales-Manager");
        add("IT-Systemelektroniker");
        add("Installations- und Gebäudetechnik");
        add("Heizungstechnik");
        add("IT-Systemadministrator");
        add("IT-Systemmanager");
        add("Jurist");
        add("Journalist");
        add("Jurist");
        add("Journalist");
        add("Judaist");
        add("Jurist");
        add("Jockey");
        add("Jurist");
        add("Journalist");
        add("Jugendbetreuer");
        add("Jurist");
        add("Jurist");
        add("Jurist");
        add("Jurist");
        add("Jäger");
        add("Jurist");
        add("Jurist");
        add("Kommerzkundenbetreuer");
        add("Keramiker");
        add("Kunsthistoriker");
        add("Konstruktionstechniker");
        add("Kulturtechniker");
        add("Kunststoffverarbeitung");
        add("Konstrukteur");
        add("Kriminaltechniker");
        add("Key Account Manager");
        add("Account Manager");
        add("Kaufmann/-frau");
        add("Kurierdienste");
        add("Kongress Manager");
        add("Kraftfahrzeugtechnik");
        add("Kraftfahrzeugelektriker");
        add("Kriminalbeamter");
        add("Kriminalbeamtin");
        add("Kaufhausdetektiv");
        add("Kantineur");
        add("Kraftfahrzeugmechaniker");
        add("Kristallschleiftechnik");
        add("Kameramann/-frau");
        add("Krankenhausreferent");
        add("Konstrukteur");
        add("Maschinenbautechnik");
        add("Klavierbau");
        add("Kommunikationstechniker");
        add("Klinische/r Linguist");
        add("Komponist");
        add("Kanzleiassistent");
        add("Rechtsanwaltskanzlei");
        add("Keramiker");
        add("Gebrauchskeramik");
        add("Kleinkindpädagoge/-pädagogin");
        add("Kunststeinerzeuger");
        add("Kfz-Sachverständiger");
        add("Kfz-Sachverständige");
        add("Kunstkritiker");
        add("Kabarettist");
        add("Kommunikationstechniker");
        add("Bürokommunikation");
        add("Kommunikationstechniker");
        add("Elektronische Datenverarbeitung und Telekommunikation");
        add("KundInnenbetreuer");
        add("Kunsttherapeut");
        add("Kreditrevisor");
        add("Konstrukteur");
        add("Werkzeugbautechnik");
        add("Kognitionswissenschafter");
        add("Kinderschwester/-pfleger");
        add("Konstrukteur");
        add("Metallbautechnik");
        add("Keramiker");
        add("Industriekeramik");
        add("Kreditreferent");
        add("Kindergesundheitstrainer");
        add("Katastrophenmanager");
        add("Konstrukteur");
        add("Elektroinstallationstechnik");
        add("Kassier");
        add("Einzelhandel");
        add("Kardiotechniker");
        add("Kraftfahrzeugtechnik");
        add("Motorradtechnik");
        add("Kunstberater");
        add("Kriminologe");
        add("Kriminologin");
        add("Kellner");
        add("Kinesiologe");
        add("Kinesiologin");
        add("Kontakter");
        add("Kirchenmusiker");
        add("Kunststofftechniker");
        add("Keltologe");
        add("Keltologin");
        add("Klärwart");
        add("Karikaturist");
        add("Kartonagewarenerzeuger");
        add("Kulturwissenschafter");
        add("Kommunikationsmanager");
        add("Kulturmanager");
        add("Kosmologe");
        add("Kosmologin");
        add("Kybernetiker");
        add("Kommunikationswissenschafter");
        add("Karosseur");
        add("Kosmetiker");
        add("Kranführer");
        add("Klaviermacher");
        add("Kinderdorfmutter/-vater");
        add("Kraftfahrzeugtechnik");
        add("Personenkraftwagentechnik");
        add("Kaffeeröster");
        add("Kappenmacher");
        add("Kartograf");
        add("Kälteanlagentechnik");
        add("Kunsthändler");
        add("Kerammaler");
        add("Keramiker");
        add("Baukeramik");
        add("Kunsttischler");
        add("Küchenplaner");
        add("Kraftfahrzeugtechnik");
        add("Kerammodelleur");
        add("Kupferdrucker");
        add("Künstleragent");
        add("Kunststoffformgebung");
        add("Kindergartenassistent");
        add("Kraftfahrzeugtechnik");
        add("Nutzfahrzeugtechnik");
        add("Kolumnist");
        add("Klimatechniker");
        add("Heizungstechniker");
        add("Kürschner");
        add("Korb- und Möbelflechter");
        add("Kriminalanalytiker");
        add("Kulturvermittler");
        add("KonstrukteurIn im Fahrzeugbau");
        add("Klinischer Psychologe");
        add("Klinische Psychologin");
        add("Konsumentenberater");
        add("Kultur- und Sozialanthropolog");
        add("Klimatologe");
        add("Klimatologin");
        add("Kinder- und Jugendberater");
        add("Kinderbetreuer");
        add("Kindergärtner");
        add("Kindergartenpädagoge/-pädagogin");
        add("Kostenrechner");
        add("Kanzleiassistent");
        add("Notariat");
        add("Koch");
        add("Köchin");
        add("Kostümbildner");
        add("Kupferschmied");
        add("Küchengehilfe");
        add("Küchengehilfin");
        add("Kreditprüfer");
        add("Kurator");
        add("Konstrukteur");
        add("Installations- und Gebäudetechnik");
        add("Kommunikationstechniker");
        add("Nachrichtenelektronik");
        add("Konstrukteur");
        add("Stahlbautechnik");
        add("Kommunikationstechniker");
        add("Audio- und Videoelektronik");
        add("Kanalfacharbeiter");
        add("Krankenhausmanager");
        add("Kunststofftechnik");
        add("Karosseriebautechnik");
        add("Konzeptkünstler");
        add("Kommandant");
        add("Korrespondent");
        add("Kinderdorfhelfer");
        add("Krankenschwester/-pfleger");
        add("Konditor");
        add("Kinderkrankenschwester/-pfleger");
        add("LeiterIn des technischen Kundendienstes");
        add("LehrerIn für Bildnerische Erziehung und Werkerziehung");
        add("LehrerIn an Berufsbildenden Mittleren und Höheren Schulen");
        add("Lehrhebamme");
        add("Lagerlogistik");
        add("Lebensmittelaufsichtsorgan");
        add("Librettist");
        add("LehrerIn für Information und Kommunikation");
        add("Lektor");
        add("LehrerIn für Gesundheits- und Krankenpflege");
        add("LehrerIn für Bewegung und Sport");
        add("Landwirtschaftlicher Haushaltsberater");
        add("Landwirtschaftliche Haushaltsberaterin");
        add("Layouter");
        add("LehrerIn für Darstellende Kunst");
        add("Luftfahrzeugtechnik");
        add("Flugzeuge mit Turbinentriebwerken");
        add("Land- und Baumaschinentechnik");
        add("Baumaschinen");
        add("LebzelterIn und Wachszieher");
        add("LehrerIn an Land- und forstwirtschaftlichen Schulen");
        add("Luftfahrzeugtechniker");
        add("LehrerIn für Sozialarbeit");
        add("Ladenkassier");
        add("LehrerIn an allgemeinen Pflichtschulen");
        add("LehrerIn für Textiles Gestalten und Werkerziehung");
        add("Labortechnik");
        add("Lack- und Anstrichmittel");
        add("Lebens- und Sozialberater");
        add("Lichttechniker");
        add("Liftwart");
        add("Lerncoach");
        add("Labortechnik");
        add("Biochemie");
        add("Lackiertechnik");
        add("LehrerIn für die Sekundarstufe");
        add("Berufsbildung");
        add("Lehrlingsausbilder");
        add("Land- und Baumaschinentechnik");
        add("Landmaschinen");
        add("Lagerarbeiter");
        add("Luftfahrzeugtechnik");
        add("Lerntherapeut");
        add("LehrerIn für die Sekundarstufe");
        add("Allgemeinbildung");
        add("Legasthenie- und Dyskalkulietrainer");
        add("Luftfahrzeugtechnik");
        add("Flugzeuge mit Kolbentriebwerken");
        add("Leichtflugzeugbauer");
        add("Labortechnik");
        add("LehrerIn an Allgemeinbildenden Höheren Schulen");
        add("Landwirt");
        add("Literaturwissenschafter");
        add("Lohnverrechner");
        add("LKW-Fahrer");
        add("LehrerIn für die Primarstufe");
        add("LehrerIn für Bewegung und Sport");
        add("LehrerIn für Deutsch als Fremdsprache");
        add("Landschaftsplaner");
        add("Landwirtschaftlicher Berater");
        add("Landwirtschaftliche Beraterin");
        add("Landschaftsgärtner");
        add("LehrerIn an Polytechnischen Schulen");
        add("Landmaschinentechniker");
        add("Linguist");
        add("LehrerIn an Neuen Mittelschulen");
        add("LehrerIn für elementare Musik- u. Bewegungserziehung");
        add("Lebensmitteltechniker");
        add("Lerntheoretiker");
        add("Leasingspezialist");
        add("Lebensmitteltechnik");
        add("Logopäde");
        add("Logopädin");
        add("Landwirtschaftstechniker");
        add("Luftfahrzeugtechnik");
        add("Hubschrauber");
        add("Lobbyist");
        add("Leibwächter");
        add("LedergalanteriewarenerzeugerIn und Taschner");
        add("Leistungssportler");
        add("Labortechnik");
        add("Chemie");
        add("LehrerIn für den Technischen und Gewerblichen Fachunterricht");
        add("LehrerIn für den ernährungswirtschaftlichen und haushaltsökonomischen Fachunterricht");
        add("Laborgehilfe");
        add("Laborgehilfin");
        add("Laserchirug");
        add("Logistiker");
        add("Laborassistent");
        add("Listbroker");
        add("LehrerIn für Inklusiv- und Sonderpädagogik");
        add("Manager");
        add("Mediafachmann/-frau");
        add("Maschinenbauingenieur");
        add("Mediaberater");
        add("Medizinisch-pharmazeutische/r Fachberater");
        add("Musikwissenschafter");
        add("Metalldesign");
        add("Gürtlerei");
        add("Multimedia-Konzeptionist");
        add("Manager");
        add("Mechatronik");
        add("Mikrotechniker");
        add("Metalltechnik");
        add("Metallbau- und Blechtechnik");
        add("Metalltechnik");
        add("Fahrzeugbautechnik");
        add("MalerIn und Beschichtungstechniker");
        add("Korrosionsschutz");
        add("Metalltechnik");
        add("Stahlbautechnik");
        add("Metalltechnik");
        add("Maschinenbautechnik");
        add("MediengestalterIn für Digital- und Printmedien");
        add("Multimedia-Redakteur");
        add("Manager");
        add("Meinungsforscher");
        add("Münzenhändler");
        add("Multimedia-Ingenieur");
        add("Masseur");
        add("Manager");
        add("Marktaufsichtsorgan");
        add("Modellschlosser");
        add("Maschinenschlosser");
        add("Mathematiker");
        add("Manager");
        add("Metallurg");
        add("Musicaldarsteller");
        add("Mobilitätsberater");
        add("Modedesigner");
        add("MalerIn und Beschichtungstechniker");
        add("Funktionsbeschichtungen");
        add("Mineraloge");
        add("Mineralogin");
        add("Möbelbautechniker");
        add("Maschinenbediener");
        add("Molekularmediziner");
        add("Montanmaschinenbautechniker");
        add("Maschinenfertigungstechnik");
        add("Mathematiker");
        add("Messerschmied");
        add("Marionettenspieler");
        add("Puppenspieler");
        add("Metalltechnik");
        add("Schweißtechnik");
        add("Mediensprecher");
        add("Matrose");
        add("Matrosin");
        add("Medizintechnischer Fachberater");
        add("Medizintechnische Fachberaterin");
        add("Manager");
        add("Metallbearbeitung");
        add("Manager");
        add("Mechatronik");
        add("Büro- und EDV-Systemtechnik");
        add("Mobilitätsservice");
        add("Metalltechnik");
        add("Stahlbautechnik");
        add("Musiklehrer");
        add("Material- und Verarbeitungstechniker");
        add("Manager");
        add("Medizinprodukteberater");
        add("Medienfachmann/-frau");
        add("Mediendesign");
        add("Materialprüfer");
        add("Mechatronik");
        add("Elektromaschinentechnik");
        add("Multimedia-Software-Entwickler");
        add("Maurer");
        add("Mechatronik");
        add("Mediengestalter");
        add("Medienmanager");
        add("Militärstreife");
        add("Metallgestalter");
        add("Musikalienhändler");
        add("Musikagent");
        add("Modehändler");
        add("Medizinproduktekaufmann/-frau");
        add("Mediendidaktiker");
        add("Meteorologe");
        add("Meteorologin");
        add("Maschinennäher");
        add("Miedererzeuger");
        add("Mikrotechniker");
        add("Museumsführer");
        add("Mechatronik");
        add("Alternative Antriebstechnik");
        add("Mannequin");
        add("Dressman");
        add("Molekularbiologe");
        add("Molekularbiologin");
        add("Motorradtechniker");
        add("Mathematiker");
        add("Mineur");
        add("Merchandiser");
        add("Museumsdidaktiker");
        add("Moderator");
        add("Metalltechnik");
        add("Metallbautechnik");
        add("Möbelmonteur");
        add("Mediator");
        add("Metallbaukonstrukteur");
        add("Modellbauer");
        add("Molekular-Techniker");
        add("Management-Accountant");
        add("Metalltechnik");
        add("Zerspanungstechnik");
        add("MetallschleiferIn und Galvaniseur");
        add("Museumsdirektor");
        add("Medizinischer Biometriker");
        add("Medizinische Biometrikerin");
        add("Markscheider");
        add("Mikrotechnik");
        add("Mikrotechniker");
        add("Mikrosystemtechniker");
        add("Multimedia-Projektleiter");
        add("Museumsaufseher");
        add("Medizinisch-technische Fachkraft");
        add("MediengestalterIn Bild und Ton");
        add("Metalltechnik");
        add("Blechtechnik");
        add("MalerIn und Beschichtungstechniker");
        add("Historische Maltechnik");
        add("Medizintechniker");
        add("Metalldesign");
        add("Musiker");
        add("Metalltechnik");
        add("Schmiedetechnik");
        add("Marketing-Manager");
        add("Mechatronik");
        add("Automatisierungstechnik");
        add("Medizininformatiker");
        add("Mechatronik");
        add("Medizingerätetechnik");
        add("Metalltechnik");
        add("Musiktherapeut");
        add("Molkereifachmann");
        add("Manager");
        add("Milchtechnologie");
        add("Maschinenmechanik");
        add("Mikrobiologe");
        add("Mikrobiologin");
        add("Mediaplaner");
        add("Maler");
        add("Modelltischler");
        add("Managementassistent");
        add("Medienfachmann/-frau");
        add("Marktkommunikation und Werbung");
        add("Metalldrücker");
        add("Marketingfachmann/-frau");
        add("Metallurgie und Umformtechnik");
        add("Maschinenbautechnik");
        add("Maskenbildner");
        add("Manager");
        add("Medienarchivar");
        add("Mikrotechniker");
        add("Mikrotechniker");
        add("Manager");
        add("Metallgießer");
        add("Modist");
        add("Multimedia-Projektmanager");
        add("Multimedia-Producer");
        add("Müllaufleger");
        add("Multimedia-Künstler");
        add("Medienfachmann/-frau");
        add("Medientechnik");
        add("Mechatronik");
        add("Fertigungstechnik");
        add("Museumspädagoge");
        add("Museumspädagogin");
        add("Markt- und Meinungsforscher");
        add("Multimedia-Informatiker");
        add("Meeresbiologe");
        add("Meeresbiologin");
        add("Musikmanager");
        add("Modegrafiker");
        add("Multimedia-Programmierer");
        add("Metalltechnik");
        add("Fahrzeugbautechnik");
        add("Mountainbike- und Touringguide");
        add("Maschinsticker");
        add("Manager");
        add("Medizinischer Masseur");
        add("Medizinische Masseurin");
        add("Manager");
        add("Maschinenbau- und Anlagenkonstrukteur");
        add("Meeresforscher");
        add("Messe- u. Ausstellungsgestalter");
        add("Multimedia-Designer");
        add("Medieninformatiker");
        add("Mechatroniker");
        add("Maschinenbautechniker");
        add("Medienkomponist");
        add("MalerIn und Beschichtungstechniker");
        add("Dekormaltechnik");
        add("Mikroelektroniker");
        add("Medizinischer Dokumentar");
        add("Medizinische Dokumentarin");
        add("Metalltechnik");
        add("Schmiedetechnik");
        add("Metallverfahrenstechniker");
        add("Metalltechnik");
        add("Metallbearbeitungstechnik");
        add("Metalldesign");
        add("Metalldrückerei");
        add("Metalltechnik");
        add("Werkzeugbautechnik");
        add("Messtechniker");
        add("MalerIn und Anstreicher");
        add("Magazineur");
        add("Metalldesign");
        add("Gravur");
        add("Mechaniker");
        add("Notfallsanitäter");
        add("Netzwerk-Designer");
        add("Night Auditor");
        add("Numismatiker");
        add("Netzwerk-Manager");
        add("Netzwerkarchitekt");
        add("Netzwerk-Administrator");
        add("Nachrichtenelektroniker");
        add("Nachrichtentechniker");
        add("New Media Consultant");
        add("Nanotechniker");
        add("Nationalpark-Ranger");
        add("Neurolinguist");
        add("Netzwerk-Expert");
        add("Nachtportier");
        add("Netzwerkbetreuer");
        add("Nachhaltigkeitsmanager");
        add("Notar");
        add("Nanotechnologe");
        add("Nanotechnologin");
        add("Neurowissenschafter");
        add("Nanobiotechnologe");
        add("Nanobiotechnologin");
        add("Netzwerkverwalter");
        add("Netzwerktechniker");
        add("Nahrungsmittelanalytiker");
        add("Optischer Elektroniker");
        add("Optische Elektronikerin");
        add("Orthoptist");
        add("Operations Controller");
        add("Flugverkehr");
        add("Ozeanograf");
        add("Oberflächentechnik");
        add("Pulverbeschichtung");
        add("Oberflächentechnik");
        add("Mechanische Oberflächentechnik");
        add("Orthopädietechnik");
        add("Prothesentechnik");
        add("Öko-Designer");
        add("Optiker");
        add("Operationsgehilfe");
        add("Operationsgehilfin");
        add("Ökosystemwissenschafter");
        add("Ökologieberater");
        add("Outplacer");
        add("Online Editor");
        add("Obduktionsassistent");
        add("OffizierIn des Truppendienstes");
        add("Oberflächentechnik");
        add("Galvanik");
        add("Orthopädiemechaniker");
        add("Ordinationsgehilfe");
        add("Ordinationsgehilfin");
        add("Öko-Consultant");
        add("Office Manager");
        add("Operationsassistent");
        add("Ökobaumeister");
        add("Obst- und Gemüsekonservierer");
        add("Ordensmann");
        add("Ofenbau- und Verlegetechnik");
        add("Online-Redakteur");
        add("Öko-Auditor");
        add("Ordensfrau");
        add("OffizierIn des höheren militärtechnischen Dienstes");
        add("Orgelbau");
        add("Osteopath");
        add("Orthopädietechnik");
        add("Orthopädietechnik");
        add("Orthesentechnik");
        add("Ordinationsassistent");
        add("OffizierIn des Generalstabsdienstes");
        add("Oberteilherrichter");
        add("Ökologe/Ökologin");
        add("Oberflächentechnik");
        add("Emailtechnik");
        add("Orthopädieschuhmacher");
        add("Online-Journalist");
        add("OffizierIn des Intendanzdienstes");
        add("Orgelbauer");
        add("OffizierIn des technischen Dienstes");
        add("Ökoenergieinstallationstechniker");
        add("Oberflächentechnik");
        add("Orthopädietechnik");
        add("Rehabilitationstechnik");
        add("Oberflächentechnik");
        add("Feuerverzinkung");
        add("Oberflächentechniker");
        add("Organisationsberater");
        add("Portier");
        add("Produktmanager");
        add("Politologe");
        add("Politologin");
        add("Prosekturgehilfe");
        add("Prosekturgehilfin");
        add("Porzellanformer");
        add("Physiker");
        add("Paläontologe");
        add("Paläontologin");
        add("Pharmatechnologie");
        add("Psychotherapeut");
        add("Paläograf");
        add("Partnervermittler");
        add("Publizist");
        add("Personalleiter");
        add("Polier");
        add("Pflegefachassistent");
        add("Präparator");
        add("Projektmanager");
        add("Personenbetreuer");
        add("Philosoph");
        add("Pressesprecher");
        add("Plakatierer");
        add("PostbediensteteR");
        add("Prozessleittechniker");
        add("Projektleiter");
        add("Pre-Sales-Consultant");
        add("Platten- und Fliesenleger");
        add("Philologe");
        add("Philologin");
        add("Produktionsleiter");
        add("PostbediensteteR");
        add("Physiotherapeut");
        add("Petrochemiker");
        add("Pädagoge");
        add("Pädagogin");
        add("Pädagoge");
        add("Pädagogin");
        add("Pädagoge");
        add("Pädagogin");
        add("Pharmareferent");
        add("Pferdepfleger");
        add("Pädagoge");
        add("Pädagogin");
        add("Polizist");
        add("Platzmeister");
        add("Pfandleiher");
        add("Pflanzenschutzberater");
        add("Pflegefachkraft");
        add("Pflasterer");
        add("Pflasterin");
        add("Personalentwickler");
        add("Physiklaborant");
        add("Produktionsleiter");
        add("Pharmakologe");
        add("Pharmakologin");
        add("Personalverrechner");
        add("Pantomimenspieler");
        add("Polymerchemiker");
        add("Primarstufenlehrer");
        add("Pädagoge");
        add("Pädagogin für Inklusive Sozialpädagogik");
        add("Pädagoge");
        add("Pädagogin");
        add("Posamentierer");
        add("Pädagoge");
        add("Pädagogin");
        add("Planungskoordinator");
        add("Priester");
        add("Privatkundenbetreuer");
        add("Personal Consultant");
        add("Personaldienstleistung");
        add("Patentanwalt");
        add("Patentanwältin");
        add("Pilot");
        add("Personalberater");
        add("Partyveranstalter");
        add("PostbediensteteR");
        add("Pflegeassistent");
        add("Papiermaschinenarbeiter");
        add("Pädagoge");
        add("Pädagogin");
        add("Pfarrer");
        add("Physiker");
        add("Prozesstechnik");
        add("Patissier");
        add("Produzent");
        add("Produktionstechniker");
        add("PR-Berater");
        add("Prozessplaner");
        add("Pilatestrainer");
        add("Produktentwickler");
        add("Pflegehelfer");
        add("Pädagoge");
        add("Pädagogin");
        add("Performancekünstler");
        add("Pannenfahrer");
        add("Psychiatrische/r Gesundheits- und Krankenpfleger");
        add("Platzwart");
        add("Pädagoge");
        add("Pädagogin");
        add("Pressefotograf");
        add("Personalsachbearbeiter");
        add("Prozessmanager");
        add("Patent Professional");
        add("Polsterer");
        add("Polsterin");
        add("Psychologe");
        add("Psychologin");
        add("Pharmazeut");
        add("PostbediensteteR");
        add("Physiker");
        add("Politiker");
        add("Pastoralassistent");
        add("Präzisionswerkzeugschleiftechnik");
        add("Portfoliomanager");
        add("Prozesstechniker");
        add("Pyrotechniker");
        add("Pharmazeutisch-kaufmännische Assistenz");
        add("Papiertechnik");
        add("Parkraumüberwacher");
        add("Porzellanmaler");
        add("Pferdewirt");
        add("Qualitätsmanager");
        add("Quantenphysiker");
        add("Qualitätssicherungstechniker");
        add("Quanten-Techniker");
        add("QualitätstechnikerIn im Fahrzeugbau");
        add("Qi-Gong-Lehrer");
        add("Robotiktechniker");
        add("Raumpfleger");
        add("Requisiteur");
        add("Regieassistent");
        add("Reiseverkehrsfachmann/-frau");
        add("Rhythmiklehrer");
        add("Raumgestalter");
        add("Radiosprecher");
        add("Röntgenassistent");
        add("Reprografie");
        add("Religionslehrer");
        add("Regalbetreuer");
        add("Recyclingtechniker");
        add("Rating-Analyst");
        add("Rohrleitungsmonteur");
        add("Regelungs- und Automatisierungstechniker");
        add("Rechtswissenschafter");
        add("Raumplaner");
        add("Rotgerber");
        add("Restaurantfachmann/-frau");
        add("Radiologietechnologe");
        add("Radiologietechnologin");
        add("Religionslehrer");
        add("Rauwarenzurichter");
        add("Religionswissenschafter");
        add("Risiko-Manager");
        add("Reiseleiter");
        add("Retail Manager");
        add("Referent");
        add("Reiki-Praktiker");
        add("Rettungsfahrer");
        add("Recruiter");
        add("Rechtsanwalt");
        add("Rechtsanwältin");
        add("Restaurator");
        add("Rauchfangkehrer");
        add("Radio- und Fernsehredakteur");
        add("Recording Engineer");
        add("Regionalberater");
        add("Regisseur");
        add("REFA-Techniker");
        add("Rabbiner");
        add("Reporter");
        add("Rettungssanitäter");
        add("Richter");
        add("Rechtskanzleiassistent");
        add("Redakteur");
        add("Restaurator");
        add("Reinigungstechnik");
        add("Reisebüroassistent");
        add("Revisionsassistent");
        add("Rezeptionist");
        add("Rechtspfleger");
        add("Revisor");
        add("Reitlehrer");
        add("Romanist");
        add("Schwimmlehrer");
        add("Schulsozialarbeiter");
        add("Sachwalter");
        add("Sachbearbeiter");
        add("Hoheitsverwaltung");
        add("Schädlingsbekämpfer");
        add("Sonderpädagoge");
        add("Sonderpädagogin");
        add("Schiffsbautechniker");
        add("Speditionskaufmann/-frau");
        add("Sanitär- und Klimatechnik");
        add("Gas- und Wasserinstallation");
        add("StuckateurIn und Trockenausbauer");
        add("Schuharbeiter");
        add("Straßenerhaltungsfachmann/-frau");
        add("Schuhfertigung");
        add("Steuerassistenz");
        add("Sprecher");
        add("Skierzeuger");
        add("Schulwart");
        add("Sekretär");
        add("Steingutdesigner");
        add("Straßenwärter");
        add("SFX Supervisor");
        add("Sportwissenschafter");
        add("Skibautechnik");
        add("Stellwerksmitarbeiter");
        add("Starkstrommonteur");
        add("Social Media Experte");
        add("Social Media Expertin");
        add("Surflehrer");
        add("Systemgastronomiefachmann/-frau");
        add("Schmuckdesigner");
        add("Staatsanwalt");
        add("Staatsanwältin");
        add("Streich- und Saiteninstrumentenbau");
        add("Schilehrer");
        add("Sporttherapeut");
        add("Software-Lektor");
        add("Schriftsteller");
        add("Saatbautechniker");
        add("Solartechniker");
        add("Soziologe");
        add("Soziologin");
        add("Snowboardlehrer");
        add("Sound-Designer");
        add("Solosänger");
        add("Schadensgutachter");
        add("Sänger");
        add("Schuhmacher");
        add("Speditionslogistik");
        add("Süßwarenhersteller");
        add("Studiotechniker");
        add("Säuglingsschwester/-pfleger");
        add("Schwarzdecker");
        add("Stationsassistent");
        add("Software-Techniker");
        add("Sozial- und Wirtschaftsstatistiker");
        add("Software-Architekt");
        add("Schaltungstechniker");
        add("Schuldnerberater");
        add("Streich- und Saiteninstrumentenbau");
        add("Bogen");
        add("Sachbearbeiter");
        add("Steuerungs- und Regelungstechniker");
        add("Single-Berater");
        add("Sensortechniker");
        add("Sattlerei");
        add("Fahrzeugsattlerei");
        add("Shaper");
        add("Shop-Betreuer");
        add("Sattlerei");
        add("Taschnerei");
        add("Stewardess");
        add("Steward");
        add("Slawist");
        add("Staplerfahrer");
        add("Signaltechniker");
        add("Software-Designer");
        add("Stenotypist");
        add("Phonotypist");
        add("Schiffbauer");
        add("Sattlerei");
        add("Reitsportsattlerei");
        add("Systemanalytiker");
        add("Statiker");
        add("Stoffdrucker");
        add("Schriftdesigner");
        add("Stahlbauschlosser");
        add("Sozialpädagoge");
        add("Sozialpädagogin");
        add("Schiffsmaschinist");
        add("Seiler");
        add("System-Administrator");
        add("Software-Betreuer");
        add("Sozialmanager");
        add("Streich- und Saiteninstrumentenbau");
        add("Zupfinstrumente");
        add("Schönheitspfleger");
        add("Sanitäter");
        add("Sportadministration");
        add("Sanitär- und Klimatechnik");
        add("Lüftungsinstallation");
        add("Schaler");
        add("Streich- und Saiteninstrumentenbau");
        add("Streichinstrumente");
        add("Schweißer");
        add("Stuntman");
        add("Stuntwoman");
        add("Sales Manager");
        add("Schmied");
        add("Schmerztherapeut");
        add("SystementwicklerIn für Multimedia");
        add("Schalungsbau");
        add("Sportlehrer");
        add("Seilbahntechnik");
        add("Steuer- und Wirtschaftsprüfer");
        add("Servierkraft");
        add("Sanitätsgehilfe");
        add("Sanitätsgehilfin");
        add("SPS-Techniker");
        add("Software-Programmierer");
        add("Sozialwirt");
        add("Schneider");
        add("Sanitär- und Klimatechnik");
        add("Ökoenergieinstallation");
        add("Sexualpädagoge");
        add("Sexualpädagogin");
        add("Schiffssteuermann/-frau");
        add("Sicherheitsfachkraft");
        add("Sachbearbeiter");
        add("Landesverwaltung");
        add("Software-Engineer");
        add("Schulpsychologe");
        add("Schulpsychologin");
        add("Supply Chain Manager");
        add("Schornsteinfeger");
        add("Straßenplaner");
        add("Spediteur");
        add("Sozialforscher");
        add("Synchronsprecher");
        add("Schiffskapitän");
        add("StempelerzeugerIn und Flexograf");
        add("Statist");
        add("Standesbeamter");
        add("Standesbeamtin");
        add("Steuerberater");
        add("Strickmaschineneinrichter");
        add("Sonnenschutztechnik");
        add("Stubenmädchen/-bursch");
        add("SportgeräteherstellerIn/-monteur");
        add("Sanitär- und Klimatechnik");
        add("Heizungsinstallation");
        add("Sprengbefugter");
        add("Sprengbefugte");
        add("Schuster");
        add("Sportmanager");
        add("Sportgerätetechniker");
        add("Statistiker");
        add("Supervisor");
        add("Suchtberater");
        add("Seniorenbetreuer");
        add("Straßenbauarbeiter");
        add("Schaufenstergestalter");
        add("Stadt- und Regionalplaner");
        add("Schreiner");
        add("Servicetechniker");
        add("Segellehrer");
        add("Shiatsu-Praktiker");
        add("Sachbearbeiter");
        add("Wirtschaftsverwaltung");
        add("Screen-Designer");
        add("Starkstromtechniker");
        add("Software-Ingenieur");
        add("Stickereizeichner");
        add("Skript Consultant");
        add("Saatgutanalytiker");
        add("Sprachwissenschafter");
        add("Sodawassererzeuger");
        add("Speiseeiserzeuger");
        add("Software-Developer");
        add("Sozialhelfer");
        add("Schätzmeister");
        add("Sensal");
        add("Schirmmacher");
        add("Straßenreiniger");
        add("SattlerIn und Riemer");
        add("Strickwarenerzeuger");
        add("Schauspieler");
        add("Sägetechniker");
        add("Spengler");
        add("Software-Entwickler");
        add("Siebdrucker");
        add("Streetworker");
        add("Sozialarbeiter");
        add("Sommelier");
        add("Sommelière");
        add("Sachbearbeiter");
        add("Öffentlicher Baudienst");
        add("Schlosser");
        add("Souffleur");
        add("Souffleuse");
        add("Säckler");
        add("Sprachlehrer");
        add("Steinmetz");
        add("Systemwissenschafter");
        add("Straßenbahnfahrer");
        add("Sporttechnologe");
        add("Sporttechnologin");
        add("Stylist");
        add("Sinologe");
        add("Sinologin");
        add("SAP-Berater");
        add("Schilderherstellung");
        add("Triebwagenführer");
        add("Tennislehrer");
        add("Tontechniker");
        add("Rundfunk");
        add("Traffic-Clerk");
        add("Trickfilmzeichner");
        add("Comic Zeichner");
        add("Tanzpädagoge");
        add("Tanzpädagoin");
        add("Textiltechnologie");
        add("Turkologe");
        add("Turkologin");
        add("Tänzer");
        add("Tunnelbautechniker");
        add("Textilchemie");
        add("TierpflegerIn mit Schwerpunkt Forschung und Klinik");
        add("Tauchlehrer");
        add("Tissue Engineer");
        add("Textilreiniger");
        add("Textilmusterzeichner");
        add("Transportbetontechnik");
        add("Tele-Tutor");
        add("Theaterwissenschafter");
        add("Textilveredler");
        add("Tiefbauer");
        add("TätowiererIn und Piercer");
        add("Theologe");
        add("Theologin");
        add("Technokeramformer");
        add("Textiltechnik");
        add("Maschentechnik");
        add("Taucher");
        add("Tanzlehrer");
        add("Telematiker");
        add("Tierpfleger");
        add("Toningenieur");
        add("Textilgestaltung");
        add("Strickwaren");
        add("Tontechniker");
        add("Aufnahmeleitung");
        add("Triebfahrzeugführer");
        add("Toxikologe");
        add("Toxikologin");
        add("Teamassistent");
        add("Treasury-Manager");
        add("TierpflegerIn mit Schwerpunkt Tierheime");
        add("Tischlereitechnik");
        add("Produktion");
        add("Technischer Zeichner");
        add("Tankwagenfahrer");
        add("Trendscout");
        add("TapeziererIn und Dekorateur");
        add("Tankwart");
        add("Transportarbeiter");
        add("Tourismusmanager");
        add("Textilkaufmann/-frau");
        add("Textilgestaltung");
        add("Weberei");
        add("Tagungsveranstalter");
        add("Tiefbautechniker");
        add("Textildesigner");
        add("Tiefdruckformenhersteller");
        add("Third Age Coach");
        add("Tierhändler");
        add("Tourismusberater");
        add("TrauerrednerIn und Ritualbegleiter");
        add("Technischer Lektor");
        add("Technische Lektorin");
        add("Treuhandassistent");
        add("Tourismuskaufmann/-frau");
        add("Textilgestaltung");
        add("Posamentiererei");
        add("Tontechniker");
        add("Live-Tontechnik");
        add("TapeziererIn und Bettwarenerzeuger");
        add("Trafikant");
        add("Textilgestaltung");
        add("Stickerei");
        add("Technischer Redakteur");
        add("Technische Redakteurin");
        add("Tierpsychologe");
        add("Tierpsychologin");
        add("Textiltechniker");
        add("Tabakarbeiter");
        add("Tierarzthelfer");
        add("Terrazzomacher");
        add("Tonmeister");
        add("Tontechniker");
        add("Tischlereitechnik");
        add("Planung");
        add("Tontechniker");
        add("Film");
        add("Trainer");
        add("TierpflegerIn mit Schwerpunkt Zoo");
        add("Tagesmutter/-vater");
        add("Tischlereitechnik");
        add("Trainer");
        add("Textiltechnik");
        add("Webtechnik");
        add("Textilmechanik");
        add("Tierarzt");
        add("Tierärztin");
        add("Tontechniker");
        add("Theater");
        add("Technical Support Engineer");
        add("Telefonist");
        add("Tischlerei");
        add("Technischer Offizier");
        add("Technische Offizierin");
        add("Taxifahrer");
        add("Übersetzer");
        add("Umweltsystemwissenschafter");
        add("Unternehmensberater");
        add("Umwelttechniker");
        add("Umweltberater");
        add("Usability Engineer");
        add("Unternehmensberater");
        add("Unternehmensberater");
        add("Unternehmensberater");
        add("Universitätsdozent");
        add("Uhrmacher");
        add("Zeitmesstechniker");
        add("Universalhärter");
        add("Unternehmensberater");
        add("Umweltmesstechniker");
        add("Umweltanalytiker");
        add("Unternehmer");
        add("U-Bahn-Fahrer");
        add("Universitätslektor");
        add("Umweltbautechniker");
        add("Unternehmensberater");
        add("Unternehmensberater");
        add("Umweltingenieur");
        add("Unteroffizier");
        add("Unternehmensberater");
        add("Umweltgutachter");
        add("Unternehmensberater");
        add("UmweltbeauftragteR");
        add("Universitätsprofessor");
        add("Universitätsassistent");
        add("Umwelt- und Nachhaltigkeitsmanager");
        add("Umweltverfahrenstechniker");
        add("Unternehmensberater");
        add("Unternehmensberater");
        add("Übungsschullehrer");
        add("Universalschweißer");
        add("Völkerkundler");
        add("VerlegerIn, Verlagsfachfrau/-mann");
        add("Verwaltungsjurist");
        add("Vulkanisierung");
        add("Verbandstoffarbeiter");
        add("Videojournalist");
        add("Vermessungstechniker");
        add("Vertriebswirt");
        add("Verkäufer");
        add("Versicherungsberater");
        add("Versicherungsfachfrau/-mann");
        add("Inkasso");
        add("Vollzeit-Betreuer");
        add("Volkswirt");
        add("Vorarbeiter");
        add("Visual-Effects-Artist");
        add("Verfahrenstechniker");
        add("VergolderIn und Staffierer");
        add("Vertriebstechniker");
        add("Verfahrenstechnik für die Getreidewirtschaft");
        add("Versorgungstechniker");
        add("Versicherungsstatistiker");
        add("Veterinärmediziner");
        add("VFX Supervisor");
        add("Verkehrstechniker");
        add("Versicherungsagent");
        add("Visagist");
        add("Verfahrenstechnik für die Getreidewirtschaft");
        add("Futtermittelherstellung");
        add("Verpackungstechnik");
        add("Verhaltensforscher");
        add("Viehhändler");
        add("Verwaltungsassistent");
        add("Volksschullehrer");
        add("Verkehrstelematiker");
        add("Verkaufstechniker");
        add("Vertriebstechniker");
        add("Vermögensberater");
        add("Veranstaltungstechnik");
        add("Verfahrenstechnik für die Getreidewirtschaft");
        add("Backmittelherstellung");
        add("Versicherungsvermittler");
        add("Vergolder");
        add("Verbundstofftechniker");
        add("Vitaltrainer");
        add("Versicherungsfachfrau/-mann");
        add("Außendienst");
        add("Verschieber");
        add("Verwaltungsfachbeamter");
        add("Verwaltungsfachbeamtin");
        add("Versicherungsfachfrau/-mann");
        add("Schadensreferate");
        add("Verlagslektor");
        add("Versicherungsfachmann/-frau");
        add("Versicherungsmakler");
        add("Versicherungsmathematiker");
        add("Versicherungsfachfrau/-mann");
        add("Innendienst");
        add("Volkskundler");
        add("Vermessungstechniker");
        add("Verkehrspsychologe");
        add("Verkehrspsychologin");
        add("Versicherungsvertreter");
        add("Verschlüsselungstechniker");
        add("Verkehrsökonom");
        add("Vermessungsgehilfe");
        add("Vermessungsgehilfin");
        add("Verkehrsplaner");
        add("Verfahrenstechnik für die Getreidewirtschaft");
        add("Getreidemüller");
        add("Verkehrswirtschafter");
        add("Versicherungskaufmann/-frau");
        add("Websitegestalter");
        add("Wissenschaftstheoretiker");
        add("Wirtschaftstreuhänder");
        add("Waldpädagoge");
        add("Waldpädagogin");
        add("Wasserbautechniker");
        add("Wäschewarenerzeuger");
        add("Wettannehmer");
        add("Wasserschilehrer");
        add("Wirtschaftsgeograf");
        add("Wirtschaftsprüfer");
        add("Werkzeugmacher");
        add("Weinhändler");
        add("Werbeberater");
        add("Web-Content-Manager");
        add("Werkzeugbautechnik");
        add("Werkmeister");
        add("Wissenschaftshistoriker");
        add("Wirtschafter");
        add("Werbetexter");
        add("Werkstoffingenieur");
        add("Werbegrafik-Designer");
        add("Werkstofftechnik");
        add("Weingartenarbeiter");
        add("Web-Designer");
        add("Wirbelsäulentrainer");
        add("Wächter");
        add("Wirtschaftsforscher");
        add("Wertpapieranalyst");
        add("Wäschenäher");
        add("Wirtschaftspädagoge");
        add("Wirtschaftspädagogin");
        add("Werbefachmann/-frau");
        add("Werkstofftechnik");
        add("Werkstoffprüfung");
        add("Wissensmanager");
        add("Werbemittler");
        add("Werkzeugmaschineur");
        add("Werbefotograf");
        add("Winzer");
        add("WäscherIn und Wäschebügler");
        add("Wirtschaftsingenieur");
        add("Wellnesstrainer");
        add("Werbe- und Medienvorlagenhersteller");
        add("Wirtschaftsmathematiker");
        add("Web-Developer");
        add("Wärmebehandlungstechnik");
        add("Wirtschaftsberater");
        add("Wirtschaftscoach");
        add("Weber");
        add("Werbegestalter");
        add("Wasserleitungsinstallateur");
        add("Wirtschaftstechniker");
        add("Werkstofftechniker");
        add("Wertpapierberater");
        add("Waffenbautechniker");
        add("Weiß- und Sämischgerber");
        add("Wertpapierhändler");
        add("Weinhauer");
        add("Waffenmechaniker");
        add("Werkstofftechniker");
        add("Schwerpunkt Verbundstoffe");
        add("Weinbautechniker");
        add("Web-Master");
        add("Waffelbäcker");
        add("Werkzeugkonstrukteur");
        add("Wirkwarenerzeuger");
        add("Waffen- und Munitionshändler");
        add("Wirtschaftsinformatiker");
        add("Werkzeugmechanik");
        add("Waagenhersteller");
        add("Wagner");
        add("Website-Programmierer");
        add("Werkstättenleiter");
        add("Yoga Lehrer");
        add("Zahnarzt/-ärztin");
        add("Zellstofftechniker");
        add("Zinngießer");
        add("Ziviltechniker");
        add("Zugrevisor");
        add("Zoofachhändler");
        add("Zellstoffhersteller");
        add("Zahntechnischer Laborant");
        add("Zahntechnische Laborantin");
        add("Zimmerei");
        add("Zahnärztliche Fachassistenz");
        add("Zugbegleiter");
        add("Zolldeklarant");
        add("Zahnärztlicher Assistent");
        add("Zahnärztliche Assistentin");
        add("Zahnarzthelfer");
        add("Zweiradtechniker");
        add("Zauberkünstler");
        add("Zerspanungstechnik");
        add("Zoolog");
        add("Zimmereitechnik");
        add("Zahntechniker");
        add("Zimmerer");
        add("Zentralheizungsbauer");
        add("Zeitungszusteller");
    }};
}
